--
-- Database: `dinterminal`
--
USE dinterminal;
--
-- Data dump for tabellen `crm_queries`
--

INSERT INTO `crm_queries` (`query_id`, `query_owner`, `query_active`, `query_name`, `query_type`, `query_database`, `query_content`, `query_uid`, `query_groups`, `query_used`) VALUES
(4, 1, 1, 'Newest 10 merchants', 'LIST', 'dinterminal', 'SELECT merchantid, cvr_name FROM customer_cvr ORDER BY merchantid DESC limit 10', '0', '0', 0),
(5, 1, 1, 'Total Transactions in Yourpay', 'COUNT', 'dinterminalpayments', 'SELECT PaymentID FROM 02_payments', '0', '0', 0),
(6, 1, 1, 'Newest 10 customers of Dinero', 'LIST', 'dinterminal', 'SELECT merchantid, cvr_name FROM customer_cvr WHERE psper = 1277 OR psper = 1280 ORDER BY merchantid DESC LIMIT 10', '0', '0', 0),
(7, 1, 1, 'E-mails sent by Yourpay today', 'COUNT', 'dinterminal', 'SELECT MailID FROM MailQueue WHERE registered >CURDATE()', '0', '0', 0),
(8, 1, 1, 'Callbacks Requested today', 'COUNT', 'dinterminalpayments', 'SELECT * FROM 02_callbacks WHERE unixtime>UNIX_TIMESTAMP(CURDATE())', '0', '0', 0),
(9, 1, 1, 'Callbacks in Queue right now', 'COUNT', 'dinterminalpayments', 'SELECT UniqueID FROM 02_callbacks WHERE unixtime>UNIX_TIMESTAMP(CURDATE()) AND callbackstatus=\'0\'', '0', '0', 0),
(10, 1, 1, 'Callbacks Completed Today', 'COUNT', 'dinterminalpayments', 'SELECT UniqueID FROM 02_callbacks WHERE unixtime>UNIX_TIMESTAMP(CURDATE()) AND callbackstatus=\'1\'', '0', '0', 0),
(11, 1, 1, 'Transactions Completed Today', 'COUNT', 'dinterminalpayments', 'SELECT UniqueID FROM 02_payments WHERE restimestamp>UNIX_TIMESTAMP(CURDATE())', '0', '0', 0),
(12, 1, 1, 'Transactions Captured Today', 'COUNT', 'dinterminalpayments', 'SELECT ActionID FROM 02_paymentcapture WHERE req_timestamp>UNIX_TIMESTAMP(CURDATE()) AND captured=\'1\' AND handlingtype=\'capture\'', '0', '0', 0),
(13, 1, 1, 'Transactions Where Refund Failed - Past 30 days', 'LIST', 'dinterminalpayments', 'SELECT ActionID, PaymentID FROM 02_paymentcapture WHERE captured=\'2\' AND handlingtype=\'refund\' AND req_timestamp>UNIX_TIMESTAMP(CURDATE()-INTERVAL 30 DAY) ', '0', '0', 0),
(14, 1, 1, 'Payouts not performed - Should have been performed', 'LIST', 'dinterminal', 'SELECT customer_transfer_accounts.merchantid, (merchant_transfer_accounts_daily_overview.captured_amount)/100 AS captured_amount FROM merchant_transfer_accounts_daily_overview,customer_transfer_accounts WHERE merchant_transfer_accounts_daily_overview.accountid = customer_transfer_accounts.accountid AND released_amount = 0 AND date_expected_release < UNIX_TIMESTAMP(CURDATE()) AND date_expected_release > UNIX_TIMESTAMP(CURDATE()-INTERVAL 30 DAY)', '0', '0', 0),
(15, 1, 1, 'Unapproved Merchants with Payouts, Next 7 days', 'LIST', 'dinterminal', 'SELECT customer_transfer_accounts.merchantid, (merchant_transfer_accounts_daily_overview.captured_amount)/100 AS captured_amount FROM merchant_transfer_accounts_daily_overview,customer_transfer_accounts, customer_cvr WHERE merchant_transfer_accounts_daily_overview.accountid = customer_transfer_accounts.accountid AND customer_transfer_accounts.merchantid = customer_cvr.merchantid_prod AND customer_cvr.final_approval<2 AND released_amount = 0 AND date_expected_release > UNIX_TIMESTAMP(CURDATE()) AND date_expected_release < UNIX_TIMESTAMP(CURDATE()+INTERVAL 7 DAY)', '0', '0', 0),
(16, 1, 1, 'Payments with DateID Missing, Past 30 days', 'LIST', 'dinterminalpayments', 'SELECT PaymentID FROM 02_paymentcapture WHERE dateid = \'-3\' AND req_timestamp>UNIX_TIMESTAMP(CURDATE()-INTERVAL 30 DAY) ORDER BY PaymentID DESC', '0', '0', 0),
(17, 1, 1, 'Fee of Today', 'LIST', 'dinterminal', 'SELECT FORMAT(SUM(captured_fee)/100,2,\'da_dk\') AS fee FROM merchant_transfer_accounts_daily_overview where date_start>=UNIX_TIMESTAMP(CURDATE())', '0', '0', 0),
(18, 14, 1, 'Payment Refund Failures - Past 30 Days', 'LIST', 'dinterminalpayments', 'SELECT PaymentID FROM\r\n02_paymentcapture WHERE\r\nreq_timestamp < UNIX_TIMESTAMP (DATE_SUB(NOW(), INTERVAL 4 HOUR)) AND\r\nreq_timestamp > UNIX_TIMESTAMP (DATE_SUB(NOW(),INTERVAL 30 DAY)) AND\r\nhandlingtype = \'refund\' AND\r\n(captured = 0 OR captured = 2)\r\nORDER BY ActionID DESC', '0', '0', 0),
(19, 14, 1, 'Payment Capture Failures - Past 30 Days', 'LIST', 'dinterminalpayments', 'SELECT PaymentID FROM 02_paymentcapture WHERE\r\nreq_timestamp < UNIX_TIMESTAMP (DATE_SUB(NOW(), INTERVAL 4 HOUR)) AND\r\nreq_timestamp > UNIX_TIMESTAMP (DATE_SUB(NOW(),INTERVAL 30 DAY)) AND\r\n(captured = 0 OR captured = 2) AND\r\nhandlingtype = \'capture\'\r\nORDER BY ActionID DESC', '0', '0', 0),
(20, 14, 1, 'Payment DateID Failures - Past 30 Days', 'LIST', 'dinterminalpayments', 'SELECT PaymentID FROM \n02_paymentcapture WHERE \nreq_timestamp < UNIX_TIMESTAMP(NOW()) AND \nreq_timestamp > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY)) AND\ndateid = -3', '0', '0', 0),
(21, 14, 1, 'Payout Release Failures - Exceeded Expected Release Date - Past 30 Days', 'LIST', 'dinterminal', 'SELECT merchant_transfer_accounts_daily_overview.dateid, merchant_transfer_accounts_daily_overview.accountid, customer_transfer_accounts.merchantid FROM \r\nmerchant_transfer_accounts_daily_overview, customer_transfer_accounts WHERE \r\nmerchant_transfer_accounts_daily_overview.accountid = customer_transfer_accounts.accountid AND\r\nmerchant_transfer_accounts_daily_overview.released_amount = 0 AND \r\nmerchant_transfer_accounts_daily_overview.date_expected_release < UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 1 DAY)) AND \r\nmerchant_transfer_accounts_daily_overview.date_expected_release > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY))  \r\nGROUP BY merchantid ORDER BY `merchant_transfer_accounts_daily_overview`.`date_expected_release`  DESC', '0', '0', 0),
(22, 14, 1, 'Pending Banking imports', 'COUNT', 'dinterminal', 'SELECT COUNT(ImportID) AS ImportID FROM `merchant_outgoing_transactions` WHERE dateid=0 AND import_accepted=0\n', '0', '0', 0),
(23, 14, 1, 'Payment Release Failures - Past 30 Days', 'LIST', 'dinterminalpayments', 'SELECT PaymentID FROM \n02_paymentcapture WHERE \nreq_timestamp < UNIX_TIMESTAMP(NOW()) AND \nreq_timestamp > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY)) AND \ncaptured = 0 AND \nhandlingtype = \'release\'', '0', '0', 0),
(24, 1441, 1, 'Payout Release Failures Where Approved = No - Exceeded Expected Release Date - Past 30 Days', 'LIST', 'dinterminal', 'SELECT customer_transfer_accounts.merchantid, merchant_transfer_accounts_daily_overview.accountid, dateid\r\nFROM customer_transfer_accounts\r\nLEFT JOIN merchant_transfer_accounts_daily_overview ON customer_transfer_accounts.accountid = merchant_transfer_accounts_daily_overview.accountid\r\nLEFT JOIN customer_cvr ON customer_transfer_accounts.merchantid = customer_cvr.merchantid_prod\r\nWHERE final_approval = 0\r\nAND released_amount = 0\r\nAND date_expected_release < UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 1 DAY)) \r\nAND date_expected_release > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY))\r\n', '0', '0', 0),
(25, 1441, 1, 'Payout Release Failures Where Approved = Yes - Exceeded Expected Release Date - Past 30 Days', 'LIST', 'dinterminal', 'SELECT customer_transfer_accounts.merchantid, merchant_transfer_accounts_daily_overview.accountid, dateid\r\nFROM customer_transfer_accounts\r\nLEFT JOIN merchant_transfer_accounts_daily_overview ON customer_transfer_accounts.accountid = merchant_transfer_accounts_daily_overview.accountid\r\nLEFT JOIN customer_cvr ON customer_transfer_accounts.merchantid = customer_cvr.merchantid_prod\r\nWHERE final_approval = 1\r\nAND released_amount = 0\r\nAND date_expected_release < UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 1 DAY)) \r\nAND date_expected_release > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY))', '0', '0', 0),
(26, 1, 1, 'Adwords Accounts - Less than 300 DKK in revenue (Created past 30 days)', 'LIST', 'dinterminal', 'SELECT * FROM (SELECT customer_cvr.merchantid_prod AS merchantid, customer_transfer_accounts.accountid, SUM(merchant_transfer_accounts_daily_overview.captured_fee) as fee FROM customer_cvr\r\nLEFT JOIN customer_transfer_accounts\r\nON customer_cvr.merchantid_prod = customer_transfer_accounts.merchantid\r\nLEFT JOIN merchant_transfer_accounts_daily_overview\r\nON customer_transfer_accounts.accountid = merchant_transfer_accounts_daily_overview.accountid\r\n\r\nWHERE\r\npsper=1456\r\nAND customer_cvr.cvr_created < UNIX_TIMESTAMP(NOW())\r\nAND customer_cvr.cvr_created > UNIX_TIMESTAMP(DATE_SUB(NOW(),INTERVAL 30 DAY))\r\nGROUP BY merchantid_prod\r\n) AS s\r\nWHERE \r\n(s.fee < 30000 OR s.fee IS NULL)', '0', '0', 0),
(27, 1, 1, 'Transactions verified but DateID is empty', 'LIST', 'dinterminalpayments', 'SELECT ActionID, PaymentID FROM 02_paymentcapture WHERE req_timestamp < UNIX_TIMESTAMP (DATE_SUB(NOW(), INTERVAL 4 HOUR)) AND\r\nreq_timestamp > UNIX_TIMESTAMP (DATE_SUB(NOW(),INTERVAL 30 DAY)) AND\r\nhandlingtype = \'capture\' AND captured = 1 AND capture_state = \'ACK\' AND PaymentID != 0 AND dateid = 0 AND FinanceID > 0 AND payment_institute IN (1,4,20)', '0', '0', 0),
(28, 1, 1, 'Last year, approved accounts, group by owners birth year & Customer Type (POS/WEB)', 'LIST', 'dinterminal', 'SELECT COUNT(customer_cvr.merchantid) AS total_of_year, customer_pos AS customer_type, RIGHT(owner_date_of_birth, 2) AS birth_year FROM customer_cvr, customer_owners WHERE customer_cvr.approved=\'1\' AND customer_cvr.cvr_created > UNIX_TIMESTAMP (DATE_SUB(NOW(),INTERVAL 365 DAY)) AND customer_cvr.merchantid = customer_owners.merchantid AND customer_owners.owner_date_of_birth!=\'\' AND (RIGHT(owner_date_of_birth, 2)<(RIGHT(YEAR(CURDATE()), 2)-10) OR RIGHT(owner_date_of_birth, 2)>(RIGHT(YEAR(CURDATE()), 2))) GROUP BY birth_year, customer_pos', '0', '0', 0),
(29, 1, 1, 'Last year, approved accounts, group by owners city & Customer Type (POS/WEB)', 'LIST', 'dinterminal', 'SELECT COUNT(customer_cvr.merchantid) AS total_of_year, customer_pos AS customer_type, owner_city FROM customer_cvr, customer_owners WHERE customer_cvr.approved=\'1\' AND customer_cvr.cvr_created > UNIX_TIMESTAMP (DATE_SUB(NOW(),INTERVAL 365 DAY)) AND customer_cvr.merchantid = customer_owners.merchantid AND customer_owners.owner_city!=\'\' AND (RIGHT(owner_date_of_birth, 2)<(RIGHT(YEAR(CURDATE()), 2)-10) OR RIGHT(owner_date_of_birth, 2)>(RIGHT(YEAR(CURDATE()), 2))) GROUP BY owner_city, customer_pos\n', '0', '0', 0),
(30, 1, 1, 'Merchants last year, counted by MCC', 'LIST', 'dinterminal', 'SELECT COUNT(customer_cvr.mcc) AS mcc_count, mcc FROM customer_cvr WHERE customer_cvr.approved=\'1\' GROUP BY mcc', '0', '0', 0);